/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package penjualan.view;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import penjualan.config.Koneksi;
import penjualan.view.Laporan.LaporanBarang;
import penjualan.view.master.BarangView;
import penjualan.view.Laporan.LaporanPembelian;
import penjualan.view.Laporan.LaporanPenjualan;
import penjualan.view.LoginView;
import penjualan.view.Laporan.LaporanPelanggan;
import penjualan.view.master.PelangganView;
import penjualan.view.Laporan.LaporanPemasok;
import penjualan.view.master.PemasokView;
import penjualan.view.transaksi.AmbilPesananPembelianView;
import penjualan.view.transaksi.PembelianView;
import penjualan.view.transaksi.PemesananPembelianView;
import penjualan.view.transaksi.PenjualanView;

/**
 *
 * @author Lani
 */
public class FMenu extends javax.swing.JFrame {

    /**
     * Creates new form FMenu
     */
    public FMenu() throws SQLException {
        initComponents();
        setUser();
    }
    //-------privilege login-------//

    public void setUser() throws SQLException {
        Statement st = Koneksi.getConnection().createStatement();
        ResultSet rs = st.executeQuery("select nama, jabatan from user where status='ON'");
        if (rs.next()) {
            user.setText(rs.getString("jabatan") + " : " + rs.getString("nama"));
        }

    }

    public void loginKasir() {
        MIBarang.setVisible(false);
        MIPemasok.setVisible(false);
        MIPembelian.setVisible(false);
        MILBarang.setVisible(false);
        MILPemasok.setVisible(false);
        MIBeli.setVisible(false);
    }

    public void loginGudang() {
        MIPelanggan.setVisible(false);
        MIPemasok.setVisible(false);
        MIPenjualan.setVisible(false);
        MILPelanggan.setVisible(false);
        MILPemasok.setVisible(false);
        MITransaksi.setVisible(false);
        fdaftar.setVisible(false);
        iconLapJual.setVisible(false);
        iconPenjualan.setVisible(false);

    }
    //-------privilege login-------//

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        fdaftar = new javax.swing.JButton();
        iconPenjualan = new javax.swing.JButton();
        iconLapJual = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        user = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        MenuBar1 = new javax.swing.JMenuBar();
        MMaster = new javax.swing.JMenu();
        MIPelanggan = new javax.swing.JMenuItem();
        MIBarang = new javax.swing.JMenuItem();
        MIPemasok = new javax.swing.JMenuItem();
        MTransaksi = new javax.swing.JMenu();
        MIPembelian = new javax.swing.JMenuItem();
        mniPemesananPembelian = new javax.swing.JMenuItem();
        mniPembayaranPemesananPembelian = new javax.swing.JMenuItem();
        MIPenjualan = new javax.swing.JMenuItem();
        MLaporan = new javax.swing.JMenu();
        MILBarang = new javax.swing.JMenuItem();
        MILPelanggan = new javax.swing.JMenuItem();
        MILPemasok = new javax.swing.JMenuItem();
        MITransaksi = new javax.swing.JMenuItem();
        MIBeli = new javax.swing.JMenuItem();
        MLogout = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 153, 255));

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));
        jPanel1.setForeground(new java.awt.Color(255, 0, 255));

        fdaftar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/images.jpg"))); // NOI18N
        fdaftar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fdaftarActionPerformed(evt);
            }
        });

        iconPenjualan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/transaksi.png"))); // NOI18N
        iconPenjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iconPenjualanActionPerformed(evt);
            }
        });

        iconLapJual.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/laporan.png"))); // NOI18N
        iconLapJual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iconLapJualActionPerformed(evt);
            }
        });

        user.setFont(new java.awt.Font("Stencil Std", 0, 12)); // NOI18N
        user.setForeground(new java.awt.Color(0, 204, 204));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/pelanggan2.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(user, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(user, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(fdaftar, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                        .addComponent(iconPenjualan, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59)
                        .addComponent(iconLapJual, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)))
                .addGap(41, 41, 41))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fdaftar, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(iconPenjualan, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(iconLapJual, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(148, 148, 148)))
                .addGap(20, 20, 20))
        );

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("STC", 1, 18)); // NOI18N
        jLabel1.setText("@ZalfaMiracleSkinCare");

        MenuBar1.setBackground(new java.awt.Color(204, 204, 255));

        MMaster.setBackground(new java.awt.Color(0, 204, 204));
        MMaster.setText("MASTER");
        MMaster.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MMasterActionPerformed(evt);
            }
        });

        MIPelanggan.setText("Pelanggan");
        MIPelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MIPelangganActionPerformed(evt);
            }
        });
        MMaster.add(MIPelanggan);

        MIBarang.setText("Barang");
        MIBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MIBarangActionPerformed(evt);
            }
        });
        MMaster.add(MIBarang);

        MIPemasok.setText("Pemasok");
        MIPemasok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MIPemasokActionPerformed(evt);
            }
        });
        MMaster.add(MIPemasok);

        MenuBar1.add(MMaster);

        MTransaksi.setText("TRANSAKSI");
        MTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MTransaksiActionPerformed(evt);
            }
        });

        MIPembelian.setText("Pembelian");
        MIPembelian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MIPembelianActionPerformed(evt);
            }
        });
        MTransaksi.add(MIPembelian);

        mniPemesananPembelian.setText("Pemesanan Pembelian Barang");
        mniPemesananPembelian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniPemesananPembelianActionPerformed(evt);
            }
        });
        MTransaksi.add(mniPemesananPembelian);

        mniPembayaranPemesananPembelian.setText("Pembayaran Pemesanan Pembelian Barang");
        mniPembayaranPemesananPembelian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniPembayaranPemesananPembelianActionPerformed(evt);
            }
        });
        MTransaksi.add(mniPembayaranPemesananPembelian);

        MIPenjualan.setText("Penjualan");
        MIPenjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MIPenjualanActionPerformed(evt);
            }
        });
        MTransaksi.add(MIPenjualan);

        MenuBar1.add(MTransaksi);

        MLaporan.setText("LAPORAN");

        MILBarang.setText("Barang");
        MILBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MILBarangActionPerformed(evt);
            }
        });
        MLaporan.add(MILBarang);

        MILPelanggan.setText("Pelanggan");
        MILPelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MILPelangganActionPerformed(evt);
            }
        });
        MLaporan.add(MILPelanggan);

        MILPemasok.setText("Pemasok");
        MILPemasok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MILPemasokActionPerformed(evt);
            }
        });
        MLaporan.add(MILPemasok);

        MITransaksi.setText("Transaksi Penjualan");
        MITransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MITransaksiActionPerformed(evt);
            }
        });
        MLaporan.add(MITransaksi);

        MIBeli.setText("Transaksi Pembelian");
        MIBeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MIBeliActionPerformed(evt);
            }
        });
        MLaporan.add(MIBeli);

        MenuBar1.add(MLaporan);

        MLogout.setText("LOGOUT");
        MLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MLogoutMouseClicked(evt);
            }
        });
        MenuBar1.add(MLogout);

        setJMenuBar(MenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(329, 329, 329))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MITransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MITransaksiActionPerformed
        LaporanPenjualan tampilLaporan = new LaporanPenjualan();
        tampilLaporan.setLocationRelativeTo(null);
        tampilLaporan.setVisible(true);
    }//GEN-LAST:event_MITransaksiActionPerformed

    private void MIBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MIBarangActionPerformed
        BarangView tampilBarang = null;
        try {
            tampilBarang = new BarangView();
        } catch (SQLException ex) {
            Logger.getLogger(FMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
        tampilBarang.setLocationRelativeTo(null);
        tampilBarang.setVisible(true);
    }//GEN-LAST:event_MIBarangActionPerformed

    private void MMasterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MMasterActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_MMasterActionPerformed

    private void MIPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MIPelangganActionPerformed
        // TODO add your handling code here:
        PelangganView tampilPelanggan = new PelangganView();
        tampilPelanggan.setLocationRelativeTo(null);
        tampilPelanggan.setVisible(true);
    }//GEN-LAST:event_MIPelangganActionPerformed

    private void MTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MTransaksiActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_MTransaksiActionPerformed

    private void MIPenjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MIPenjualanActionPerformed
        PenjualanView TampilTransaksi = new PenjualanView();
        java.awt.Dimension screenRes = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        TampilTransaksi.setLocation((screenRes.width / 2) - (TampilTransaksi.getWidth() / 2), (screenRes.height / 2) - (TampilTransaksi.getHeight() / 2));
        TampilTransaksi.setVisible(true);
    }//GEN-LAST:event_MIPenjualanActionPerformed

    private void MIPembelianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MIPembelianActionPerformed

        PembelianView munculTransaksi = new PembelianView();
        munculTransaksi.setLocationRelativeTo(null);
        munculTransaksi.setVisible(true);

    }//GEN-LAST:event_MIPembelianActionPerformed

    private void MIPemasokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MIPemasokActionPerformed
        // TODO add your handling code here:
        PemasokView tampilSupplier = new PemasokView();
        tampilSupplier.setLocationRelativeTo(null);
        tampilSupplier.setVisible(true);
    }//GEN-LAST:event_MIPemasokActionPerformed

    private void MILBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MILBarangActionPerformed
        // TODO add your handling code here:
        LaporanBarang brgRep = new LaporanBarang();
        brgRep.setLocationRelativeTo(null);
        brgRep.setVisible(true);

    }//GEN-LAST:event_MILBarangActionPerformed

    private void MILPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MILPelangganActionPerformed
        // TODO add your handling code here:
        LaporanPelanggan pelRep = new LaporanPelanggan();
        pelRep.setLocationRelativeTo(null);
        pelRep.setVisible(true);
    }//GEN-LAST:event_MILPelangganActionPerformed

    private void MIBeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MIBeliActionPerformed
        // TODO add your handling code here:
        LaporanPembelian tampilLaporan = new LaporanPembelian();
        tampilLaporan.setLocationRelativeTo(null);
        tampilLaporan.setVisible(true);
    }//GEN-LAST:event_MIBeliActionPerformed

    private void MILPemasokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MILPemasokActionPerformed
        // TODO add your handling code here:
        LaporanPemasok suppRep = new LaporanPemasok();
        suppRep.setLocationRelativeTo(null);
        suppRep.setVisible(true);
    }//GEN-LAST:event_MILPemasokActionPerformed

    private void MLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MLogoutMouseClicked
        // TODO add your handling code here:

        int messageType = JOptionPane.INFORMATION_MESSAGE;
        int optionType = JOptionPane.OK_CANCEL_OPTION;
        int code = JOptionPane.showConfirmDialog(null, "Yakin ingin LogOut dari aplikasi?");
        if (code == JOptionPane.OK_OPTION) {
            this.dispose();
        } else if (code == JOptionPane.CANCEL_OPTION) {
            return;
        }

    }//GEN-LAST:event_MLogoutMouseClicked

    private void iconLapJualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iconLapJualActionPerformed
        // menampilkan form transaksi lap penjualan dengan icon:
        LaporanPenjualan tampilLapJual = new LaporanPenjualan();
        tampilLapJual.setLocationRelativeTo(null);
        tampilLapJual.setVisible(true);
    }//GEN-LAST:event_iconLapJualActionPerformed

    private void iconPenjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iconPenjualanActionPerformed
        // menampilkan form transaksi penjualan dengan icon:
        PenjualanView tampilPenjualan = new PenjualanView();
        tampilPenjualan.setLocationRelativeTo(null);
        tampilPenjualan.setVisible(true);
    }//GEN-LAST:event_iconPenjualanActionPerformed

    private void fdaftarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fdaftarActionPerformed
        // menampilkan form transaksi penjualan dengan icon:
        PelangganView tampilPelanggan = new PelangganView();
        tampilPelanggan.setLocationRelativeTo(null);
        tampilPelanggan.setVisible(true);
    }//GEN-LAST:event_fdaftarActionPerformed

    private void mniPemesananPembelianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniPemesananPembelianActionPerformed
        // TODO add your handling code here:
        PemesananPembelianView tampilPembelian = new PemesananPembelianView();
        tampilPembelian.setLocationRelativeTo(null);
        tampilPembelian.setVisible(true);
    }//GEN-LAST:event_mniPemesananPembelianActionPerformed

    private void mniPembayaranPemesananPembelianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniPembayaranPemesananPembelianActionPerformed
        // TODO add your handling code here:
        AmbilPesananPembelianView tampilPembelian = new AmbilPesananPembelianView();
        tampilPembelian.setLocationRelativeTo(null);
        tampilPembelian.setVisible(true);
    }//GEN-LAST:event_mniPembayaranPemesananPembelianActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MIBarang;
    private javax.swing.JMenuItem MIBeli;
    private javax.swing.JMenuItem MILBarang;
    private javax.swing.JMenuItem MILPelanggan;
    private javax.swing.JMenuItem MILPemasok;
    private javax.swing.JMenuItem MIPelanggan;
    private javax.swing.JMenuItem MIPemasok;
    private javax.swing.JMenuItem MIPembelian;
    private javax.swing.JMenuItem MIPenjualan;
    private javax.swing.JMenuItem MITransaksi;
    private javax.swing.JMenu MLaporan;
    private javax.swing.JMenu MLogout;
    private javax.swing.JMenu MMaster;
    private javax.swing.JMenu MTransaksi;
    private javax.swing.JMenuBar MenuBar1;
    private javax.swing.JButton fdaftar;
    private javax.swing.JButton iconLapJual;
    private javax.swing.JButton iconPenjualan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JMenuItem mniPembayaranPemesananPembelian;
    private javax.swing.JMenuItem mniPemesananPembelian;
    private javax.swing.JLabel user;
    // End of variables declaration//GEN-END:variables

    public void setVisibel(boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
